spring:
  application:
    name: media-meta-writer

server:
  port: 8666
media:
  media:
    - type: FILM
      error-directory: C:/Users/me/Media/_error
      nomatch-directory: C:/Users/me/Media/_nomatch
      destination-directory: \\ZionMedia\media\Library\Films
      source-directory: C:/Users/me/Media/_drop
#    - type: SERIES
#      source-directory: C:/Users/me/Media/_drop/Series
#      destination-directory: C:/Users/me/Media/Library/Series

tmdb:
  base-url: https://api.themoviedb.org
  api:
    configuration: /3/configuration
    movie-credits: /3/movie/{movie_id}/credits
    movie-details: /3/movie/{movie_id}
    movie-genres: /3/genre/movie/list
    movie-keywords: /3/movie/{movie_id}/keywords
    movie-release-dates: /3/movie/{movie_id}/release_dates
    movie-search: /3/search/movie
    tv-genres: /3/genre/movie/list
  access:
    key: 917f977a9db51cbf3676f8d9014b649c
    token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MTdmOTc3YTlkYjUxY2JmMzY3NmY4ZDkwMTRiNjQ5YyIsIm5iZiI6MTc2MDE4MzQwMC42MSwic3ViIjoiNjhlYTQ0Njg5N2U3ZGFmZTNiMWY2MjJmIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.ZUeezA3C6AZn47tKOKPi8mguE8KRA8OmPbglfaqbl-s


logging:
  pattern:
    console: '%msg%n'
    file: '%msg%n'